# Generated by Django 2.2.10 on 2020-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=300)),
                ('model_auto', models.CharField(max_length=100)),
                ('transmission', models.SmallIntegerField(choices=[('m', 'механика'), ('a', 'автомат'), ('r', 'робот')])),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
