# Generated by Django 2.2.10 on 2020-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('м', 'механика'), ('а', 'автомат'), ('р', 'робот')]),
        ),
    ]
