# Generated by Django 2.2.10 on 2020-09-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200923_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('механика', 'механика'), ('автомат', 'автомат'), ('робот', 'робот')]),
        ),
    ]
