# Generated by Django 2.2.10 on 2020-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200923_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('M', 'manual'), ('A', 'auto'), ('R', 'robot')], max_length=100),
        ),
    ]
