# Generated by Django 2.2.10 on 2020-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200923_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
