# Generated by Django 2.2.10 on 2020-09-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
